---
- name: Setting sysctl values
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: 1}
    - { name: "net.ipv4.conf.all.rp_filter", value: 0}
    - { name: "net.ipv4.conf.default.rp_filter", value: 0}
  when:
    - set_sysctl | bool
    - inventory_hostname in groups['neutron-l3-agent']

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "neutron-dhcp-agent"
    - "neutron-l3-agent"
    - "neutron-linuxbridge-agent"
    - "neutron-metadata-agent"
    - "neutron-openvswitch-agent"
    - "f5-openstack-agent"
    - "neutron-server"
    - "openvswitch-db-server"
    - "openvswitch-vswitchd"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "neutron-dhcp-agent"
    - "neutron-l3-agent"
    - "neutron-linuxbridge-agent"
    - "neutron-metadata-agent"
    - "neutron-openvswitch-agent"
    - "f5-openstack-agent"
    - "neutron-server"
    - "openvswitch-db-server"
    - "openvswitch-vswitchd"

- name: Copying over neutron.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/neutron.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/neutron.conf"
      - "/etc/kolla/config/neutron/{{ item }}.conf"
      - "/etc/kolla/config/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/{{ item }}/neutron.conf"
  with_items:
    - "neutron-dhcp-agent"
    - "neutron-l3-agent"
    - "neutron-linuxbridge-agent"
    - "neutron-metadata-agent"
    - "neutron-openvswitch-agent"
    - "f5-openstack-agent"
    - "neutron-server"

- name: Copying over neutron_lbaas.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/neutron_lbaas.conf.j2"
      - "/etc/kolla/config/neutron/neutron_lbaas.conf"
      - "/etc/kolla/config/neutron/{{ inventory_hostname }}/neutron_lbaas.conf"
    dest: "{{ node_config_directory }}/{{ item }}/neutron_lbaas.conf"
  with_items:
    - "neutron-server"
    - "f5-openstack-agent"

- name: Copying over ml2_conf.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/ml2_conf.ini.j2"
      - "/etc/kolla/config/neutron/ml2_conf.ini"
      - "/etc/kolla/config/neutron/{{ inventory_hostname }}/ml2_conf.ini"
    dest: "{{ node_config_directory }}/{{ item }}/ml2_conf.ini"
  with_items:
    - "neutron-dhcp-agent"
    - "neutron-l3-agent"
    - "neutron-linuxbridge-agent"
    - "neutron-metadata-agent"
    - "neutron-openvswitch-agent"
    - "neutron-server"

- name: Copying over dhcp_agent.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/dhcp_agent.ini.j2"
      - "/etc/kolla/config/neutron/dhcp_agent.ini"
    dest: "{{ node_config_directory }}/{{ item }}/dhcp_agent.ini"
  with_items:
    - "neutron-dhcp-agent"

- name: Copying over dnsmasq.conf
  template:
    src: "dnsmasq.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/dnsmasq.conf"
  with_items:
    - "neutron-dhcp-agent"

- name: Copying over l3_agent.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/l3_agent.ini.j2"
      - "/etc/kolla/config/neutron/l3_agent.ini"
    dest: "{{ node_config_directory }}/{{ item }}/l3_agent.ini"
  with_items:
    - "neutron-l3-agent"

- name: Copying over fwaas_driver.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/fwaas_driver.ini.j2"
      - "/etc/kolla/config/neutron/fwaas_driver.ini"
    dest: "{{ node_config_directory }}/{{ item }}/fwaas_driver.ini"
  with_items:
    - "neutron-l3-agent"

- name: Copying over f5-openstack-agent.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/f5-openstack-agent.ini.j2"
      - "/etc/kolla/config/neutron/f5-openstack-agent.ini"
    dest: "{{ node_config_directory }}/{{ item }}/f5-openstack-agent.ini"
  with_items:
    - "f5-openstack-agent"

- name: Copying over metadata_agent.ini
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/metadata_agent.ini.j2"
      - "/etc/kolla/config/neutron/metadata_agent.ini"
    dest: "{{ node_config_directory }}/{{ item }}/metadata_agent.ini"
  with_items:
    - "neutron-metadata-agent"
